(()=>{"use strict";const $=s=>document.querySelector(s),cv=$("#canvas"),cx=cv.getContext("2d");let ws=null,myId="",room="",host=false,players=[],state=null,running=false,paused=false,input={x:0,y:0,aimX:1,aimY:0,shoot:false},jp=null,ap=null,last=performance.now();
const url=()=>({https:"wss:",http:"ws:"}[location.protocol]+"//"+location.host);
const status=t=>$("#status").textContent=t;
function send(o){if(ws?.readyState===1)ws.send(JSON.stringify(o))}
function connect(){ws=new WebSocket(url());ws.onopen=()=>status("🟢 Máy chủ online");ws.onclose=()=>status("🔴 Mất kết nối máy chủ");ws.onerror=()=>status("🔴 Không kết nối được server");ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==="hello")myId=m.id;if(m.type==="error")status("⚠ "+m.message);if(m.type==="roomCreated"||m.type==="roomJoined"){room=m.room;players=m.players;host=players.some(p=>p.id===myId&&p.host);showRoom();}if(m.type==="playerJoined"||m.type==="playerLeft"){players=m.players;host=players.some(p=>p.id===myId&&p.host);renderPlayers()}if(m.type==="started")start(m.state);if(m.type==="snapshot"){state=m.state;hud()}}}
function showRoom(){$("#roomPanel").classList.remove("hidden");$("#roomCode").textContent=room;renderPlayers();status("🟢 Phòng "+room+" đã sẵn sàng")}
function renderPlayers(){let box=$("#players");box.innerHTML="";players.forEach(p=>{let d=document.createElement("div");d.className="player";d.innerHTML='<span class="dot"></span><span class="pname"></span><span></span>';d.children[1].textContent=(p.host?"👑 ":"")+p.name;d.children[2].textContent=p.id===myId?"BẠN":"";box.appendChild(d)});$("#start").classList.toggle("hidden",!host)}
function create(){send({type:"create",name:($("#name").value.trim()||"Player").slice(0,18)})}
function join(){let r=$("#roomInput").value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(r))return status("Mã phòng phải có 6 ký tự");send({type:"join",room:r,name:($("#name").value.trim()||"Player").slice(0,18)})}
function start(s){state=s;running=true;$("#lobby").classList.add("hidden");$("#game").classList.remove("hidden");resize();requestAnimationFrame(loop)}
function resize(){let d=Math.min(devicePixelRatio||1,1.6);cv.width=innerWidth*d;cv.height=innerHeight*d;cv.style.width=innerWidth+"px";cv.style.height=innerHeight+"px";cx.setTransform(d,0,0,d,0,0)}addEventListener("resize",resize);
function hud(){let p=state?.players?.[myId];$("#hp").textContent=Math.max(0,Math.round(p?.hp||0));$("#score").textContent=Math.round(p?.score||0);$("#count").textContent=Object.keys(state?.players||{}).length+"/4";$("#wave").textContent=state?.wave||1}
function screen(x,y){let p=state.players[myId];return{x:innerWidth/2+x-p.x,y:innerHeight/2+y-p.y}}
function draw(){cx.fillStyle="#071009";cx.fillRect(0,0,innerWidth,innerHeight);if(!state)return;let p=state.players[myId];if(!p)return;let g=64,ox=((innerWidth/2-p.x)%g+g)%g,oy=((innerHeight/2-p.y)%g+g)%g;cx.strokeStyle="#142318";for(let x=ox-g;x<innerWidth;x+=g){cx.beginPath();cx.moveTo(x,0);cx.lineTo(x,innerHeight);cx.stroke()}for(let y=oy-g;y<innerHeight;y+=g){cx.beginPath();cx.moveTo(0,y);cx.lineTo(innerWidth,y);cx.stroke()}Object.values(state.zombies||{}).forEach(z=>{let q=screen(z.x,z.y);cx.fillStyle=z.boss?"#c52f4c":"#65994f";cx.beginPath();cx.arc(q.x,q.y,z.boss?19:13,0,7);cx.fill();cx.fillStyle="#24080b";cx.beginPath();cx.arc(q.x-5,q.y-3,3,0,7);cx.arc(q.x+5,q.y-3,3,0,7);cx.fill()});Object.values(state.bullets||{}).forEach(b=>{let q=screen(b.x,b.y);cx.fillStyle="#efffb8";cx.beginPath();cx.arc(q.x,q.y,3,0,7);cx.fill()});Object.values(state.players||{}).forEach(p=>{let q=screen(p.x,p.y);cx.save();cx.translate(q.x,q.y);cx.rotate(Math.atan2(p.aimY||0,p.aimX||1));cx.fillStyle="#101710";cx.fillRect(3,-5,25,10);cx.fillStyle=p.id===myId?"#8cff65":"#63b9ff";cx.beginPath();cx.arc(0,0,15,0,7);cx.fill();cx.restore();cx.fillStyle="white";cx.font="11px system-ui";cx.textAlign="center";cx.fillText(p.name,q.x,q.y-22)})}
function loop(t){if(!running)return;let dt=Math.min(.05,(t-last)/1000);last=t;if(!paused){send({type:"input",input});draw()}requestAnimationFrame(loop)}
function joySet(x,y){let r=$("#joy").getBoundingClientRect(),dx=x-(r.left+r.width/2),dy=y-(r.top+r.height/2),l=Math.hypot(dx,dy)||1,m=48;if(l>m){dx=dx/l*m;dy=dy/l*m}input.x=dx/m;input.y=dy/m;$("#joy i").style.transform=`translate(${dx}px,${dy}px)`}
$("#joy").onpointerdown=e=>{jp=e.pointerId;$("#joy").setPointerCapture(e.pointerId);joySet(e.clientX,e.clientY)};$("#joy").onpointermove=e=>{if(e.pointerId===jp)joySet(e.clientX,e.clientY)};$("#joy").onpointerup=()=>{jp=null;input.x=input.y=0;$("#joy i").style.transform="translate(0,0)"};
cv.onpointerdown=e=>{ap=e.pointerId;cv.setPointerCapture(e.pointerId);input.shoot=true;aim(e)};cv.onpointermove=e=>{if(e.pointerId===ap)aim(e)};cv.onpointerup=()=>{ap=null;input.shoot=false};function aim(e){let p=state?.players?.[myId];if(!p)return;let q=screen(p.x,p.y);input.aimX=e.clientX-q.x;input.aimY=e.clientY-q.y}
addEventListener("keydown",e=>{if(e.key==="w"||e.key==="ArrowUp")input.y=-1;if(e.key==="s"||e.key==="ArrowDown")input.y=1;if(e.key==="a"||e.key==="ArrowLeft")input.x=-1;if(e.key==="d"||e.key==="ArrowRight")input.x=1;if(e.code==="Space")input.shoot=true});addEventListener("keyup",e=>{if(["w","s","ArrowUp","ArrowDown"].includes(e.key))input.y=0;if(["a","d","ArrowLeft","ArrowRight"].includes(e.key))input.x=0;if(e.code==="Space")input.shoot=false});
$("#create").onclick=create;$("#showJoin").onclick=()=>$("#joinBox").classList.toggle("hidden");$("#join").onclick=join;$("#start").onclick=()=>{if(host)send({type:"start"})};$("#copy").onclick=()=>navigator.clipboard?.writeText(room);$("#leave").onclick=()=>{send({type:"leave"});location.reload()};$("#pause").onclick=()=>{$("#overlay").classList.remove("hidden");paused=true};$("#resume").onclick=()=>{$("#overlay").classList.add("hidden");paused=false};$("#back").onclick=()=>location.reload();$("#roomInput").oninput=e=>e.target.value=e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);connect();resize()})();