const UI={
els:{},init(){this.els={money:document.getElementById("money"),gameMoney:document.getElementById("gameMoney"),stageName:document.getElementById("stageName"),fishName:document.getElementById("fishName"),fishLabel:document.getElementById("fishLabel"),fishHp:document.getElementById("fishHp"),fishHpText:document.getElementById("fishHpText"),lineBar:document.getElementById("lineBar"),lineText:document.getElementById("lineText"),stageProgress:document.getElementById("stageProgress"),lobbyStage:document.getElementById("lobbyStage"),shopList:document.getElementById("shopList"),skillList:document.getElementById("skillList"),stageList:document.getElementById("stageList")};this.renderAll()},
show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");},
renderAll(){let s=Game.state;this.els.money.textContent=Math.floor(s.money).toLocaleString("vi-VN");this.els.gameMoney.textContent=Math.floor(s.money).toLocaleString("vi-VN");this.els.stageName.textContent=Stages[s.stage].name;this.els.lobbyStage.textContent=Stages[s.stage].name;this.els.stageProgress.style.width=((s.stage+1)/Stages.length*100)+"%";this.shop();this.skills();this.stages()},
shop(){this.els.shopList.innerHTML=Rods.map((r,i)=>`<div class="card"><span class="tag">CẤP ${i+1}</span><div class="row"><b>🎣 ${r.name}</b><b>${r.price.toLocaleString()}💰</b></div><small>Sức kéo ×${r.power} • Dây ${r.line} • Crit ${Math.round(r.crit*100)}%</small><button ${Game.state.rod>=i?"disabled":""} onclick="Shop.buy(${i})">${Game.state.rod>=i?"✓ ĐÃ SỞ HỮU":"MUA"}</button></div>`).join("")},
skills(){this.els.skillList.innerHTML=Skills.data.map(x=>{let lv=Game.state.skill[x.id],c=Skills.cost(x);return`<div class="card"><div class="row"><b>${x.name}</b><span class="tag">LV ${lv}/${x.max}</span></div><small>${x.desc}</small><button ${lv>=x.max?"disabled":""} onclick="Skills.buy('${x.id}')">${lv>=x.max?"MAX":"NÂNG CẤP • "+c.toLocaleString()+"💰"}</button></div>`}).join("")},
stages(){this.els.stageList.innerHTML=Stages.map((x,i)=>`<div class="card"><div class="row"><b>🌊 ${x.name}</b><span class="tag">KHU ${i+1}</span></div><small>Cá mạnh ×${x.mult} • Phần thưởng cao hơn</small><button ${Game.state.stage>=i?"disabled":""} onclick="StageManager.unlock(${i})">${Game.state.stage>=i?"✓ ĐÃ MỞ":i===Game.state.stage+1?"MỞ • "+x.cost.toLocaleString()+"💰":"🔒 KHÓA"}</button></div>`).join("")},
fish(f){this.els.fishName.textContent=f.name;this.els.fishLabel.textContent=f.emoji+" "+f.name;this.els.fishHpText.textContent=`${Math.ceil(f.hp)} / ${f.maxHp}`},
update(){let f=Fishing.fish;if(f){this.els.fishHp.style.width=Math.max(0,f.hp/f.maxHp*100)+"%";this.els.fishHpText.textContent=`${Math.ceil(f.hp)} / ${f.maxHp}`;this.els.lineBar.style.width=Math.min(100,Fishing.tension)+"%";this.els.lineText.textContent=Math.round(Fishing.tension)+"%";}},
};

const Toast={timer:null,show(t){let e=document.getElementById("toast");e.textContent=t;e.classList.add("show");clearTimeout(this.timer);this.timer=setTimeout(()=>e.classList.remove("show"),1800)}};